package com.explorelk.destination.outbox;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * A catalog event waiting to be published to Kafka.
 *
 * <p>Rows are inserted in the <em>same transaction</em> as the change they
 * describe, so an event can never be lost to a crash between the database commit
 * and the Kafka send:
 *
 * <pre>
 *   BEGIN
 *     UPDATE destinations SET status = 'PUBLISHED' ...
 *     INSERT INTO outbox_events ...
 *   COMMIT
 *        |
 *   OutboxPublisher (scheduled)  ->  Kafka  ->  published_at = now()
 * </pre>
 *
 * <p>Delivery is at-least-once, so consumers must be idempotent — that is what
 * {@link #id} is for once it travels as the event id.
 *
 * <p>Deliberately the same shape as auth-service's, so the pattern reads
 * identically in both services. The one difference is that this service owns two
 * aggregates rather than one, so {@link #aggregateType} actually varies.
 */
@Entity
@Table(name = "outbox_events")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OutboxEvent {

    /**
     * Travels to Kafka as the event id; consumers dedupe on it.
     *
     * <p>Assigned by {@link OutboxWriter} rather than generated by Hibernate,
     * which is the one place this diverges from auth-service's copy. The id has
     * to be known <em>before</em> the payload is serialized, because the payload
     * carries it as {@code eventId} — that is what lets an operator take a
     * message out of Kafka UI and find the row it came from.
     */
    @Id
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** {@code DESTINATION} or {@code ATTRACTION}. */
    @Column(name = "aggregate_type", nullable = false, length = 32)
    private String aggregateType;

    /**
     * The destination or attraction id, and the Kafka partition key — so every
     * event about one entity stays ordered relative to the others. That is what
     * makes {@code ATTRACTION_UPDATED} followed by {@code ATTRACTION_ARCHIVED}
     * safe for a consumer to apply in the order it receives them.
     */
    @Column(name = "aggregate_id", nullable = false)
    private UUID aggregateId;

    /** {@code DESTINATION_PUBLISHED}, {@code ATTRACTION_UPDATED}, ... */
    @Column(name = "event_type", nullable = false, length = 48)
    private String eventType;

    /**
     * JSONB. Carries the fields a consumer needs to act without calling back —
     * an Itinerary Service that has to fetch the destination to find out what
     * changed gains nothing from the event.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "payload", nullable = false, columnDefinition = "jsonb")
    private String payload;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Null until the event reaches Kafka. The partial index covers exactly these rows. */
    @Column(name = "published_at")
    private Instant publishedAt;

    /**
     * Incremented on every failed send. Nothing gives up on a row yet — a
     * permanently poisonous event would be a bug worth fixing rather than
     * discarding — but the count is what makes one visible.
     */
    @Column(name = "attempts", nullable = false)
    @Builder.Default
    private int attempts = 0;

    // ── Behaviour ────────────────────────────────────────────────────────────

    public boolean isPublished() {
        return publishedAt != null;
    }
}
