package com.explorelk.destination.attraction;

import com.explorelk.destination.category.Category;
import com.explorelk.destination.destination.ContentStatus;
import com.explorelk.destination.destination.Destination;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.JdbcTypeCode;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

/**
 * A specific thing a traveler does or sees, belonging to exactly one
 * {@link Destination} — Nine Arches Bridge, Ella Rock, Yala Safari.
 *
 * <p>{@link #visitDurationMinutes} is the field that matters most to the rest of
 * the platform: the Itinerary Service packs attractions into days using it, so an
 * attraction with no duration cannot be planned around. That is why publishing
 * requires it.
 *
 * <p>As with {@link Destination}, the PostGIS {@code geog} column is generated by
 * the database and intentionally not mapped here.
 */
@Entity
@Table(name = "attractions")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(of = "id")
@ToString(of = {"id", "slug", "name", "status"})
public class Attraction {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * LAZY on purpose — the common query is "attractions of destination X", where
     * the destination is already loaded and an eager fetch would be a wasted
     * round trip per row.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "destination_id", nullable = false)
    private Destination destination;

    /**
     * Unique within its destination, not globally — two destinations may each have
     * a {@code main-beach}. Public lookups of a single attraction therefore use
     * the id, not the slug.
     */
    @Column(name = "slug", nullable = false, length = 80)
    private String slug;

    @Column(name = "name", nullable = false, length = 120)
    private String name;

    @Column(name = "summary", length = 300)
    private String summary;

    @Column(name = "description", columnDefinition = "text")
    private String description;

    @Column(name = "latitude", precision = 9, scale = 6)
    private BigDecimal latitude;

    @Column(name = "longitude", precision = 9, scale = 6)
    private BigDecimal longitude;

    /** The Itinerary Service's planning input. Required before publishing. */
    @Column(name = "visit_duration_minutes")
    private Short visitDurationMinutes;

    /**
     * Separate from {@link #entranceFee} because a null fee is ambiguous: "we do
     * not know yet" and "it costs nothing" are different facts and the UI shows
     * them differently.
     */
    @Column(name = "is_free", nullable = false)
    @Builder.Default
    private boolean free = false;

    /** NUMERIC(10,2). Never a floating-point type — this is money. */
    @Column(name = "entrance_fee", precision = 10, scale = 2)
    private BigDecimal entranceFee;

    @Column(name = "currency", nullable = false, length = 3)
    @Builder.Default
    private String currency = "LKR";

    @Column(name = "always_open", nullable = false)
    @Builder.Default
    private boolean alwaysOpen = false;

    /**
     * JSONB: {@code {"mon": ["06:00","18:00"], "tue": [...], ...}}. Held as a raw
     * JSON string — no entity graph for opening hours until something actually
     * queries them. Postgres validates the JSON on insert.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "opening_hours", columnDefinition = "jsonb")
    private String openingHours;

    @Column(name = "image_url", length = 500)
    private String imageUrl;

    @Column(name = "popularity_score", nullable = false)
    @Builder.Default
    private int popularityScore = 0;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 16)
    @Builder.Default
    private ContentStatus status = ContentStatus.DRAFT;

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "attraction_categories",
            joinColumns = @JoinColumn(name = "attraction_id"),
            inverseJoinColumns = @JoinColumn(name = "category_code")
    )
    @Builder.Default
    private Set<Category> categories = new LinkedHashSet<>();

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // ── Behaviour ────────────────────────────────────────────────────────────

    public boolean isPubliclyVisible() {
        return status != null && status.isPubliclyVisible();
    }

    /**
     * Publishing requires enough for a traveler to act on and for an itinerary to
     * schedule: a summary, a location, a duration, and a clear answer on cost.
     */
    public boolean isCompleteForPublishing() {
        return name != null && !name.isBlank()
                && summary != null && !summary.isBlank()
                && latitude != null && longitude != null
                && visitDurationMinutes != null
                && (free || entranceFee != null);
    }

    public void addCategory(Category category) {
        categories.add(category);
    }

    public void removeCategory(Category category) {
        categories.remove(category);
    }
}
