-- ============================================================================
-- ExploreLK Auth Service — initial schema
--
-- Conventions (see docs/auth-service.md §6):
--   * UUID primary keys, generated by gen_random_uuid() (built into PG 13+)
--   * Enums as VARCHAR + CHECK, not native ENUM types — a CHECK is a one-line
--     migration to change, ALTER TYPE is not
--   * TIMESTAMPTZ everywhere, always UTC
--   * snake_case, unquoted
-- ============================================================================


-- ────────────────────────────────────────────────────────────────────────────
-- users
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE users
(
    id                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email                 VARCHAR(255) NOT NULL,
    password_hash         VARCHAR(72)  NOT NULL,
    full_name             VARCHAR(150) NOT NULL,
    phone                 VARCHAR(30),

    role                  VARCHAR(24)  NOT NULL,
    status                VARCHAR(24)  NOT NULL,

    email_verified_at     TIMESTAMPTZ,
    provider_approved     BOOLEAN      NOT NULL DEFAULT FALSE,
    must_change_password  BOOLEAN      NOT NULL DEFAULT FALSE,

    failed_login_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMPTZ,

    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_users_role   CHECK (role   IN ('TRAVELER', 'PROVIDER', 'ADMIN', 'SUPER_ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DISABLED'))
);

-- Postgres comparisons are case-sensitive, so a plain UNIQUE(email) would let
-- both 'A@x.com' and 'a@x.com' through as two separate accounts.
-- The functional index closes that hole at the database level.
CREATE UNIQUE INDEX ux_users_email_lower ON users (LOWER(email));

-- Admin listing filters by role and status.
CREATE INDEX ix_users_role_status ON users (role, status);


-- ────────────────────────────────────────────────────────────────────────────
-- refresh_tokens
--
-- Opaque random tokens, stored as a SHA-256 hex hash — never the raw value.
-- family_id ties a rotation chain together so reuse can revoke all of it.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE refresh_tokens
(
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64) NOT NULL,
    family_id   UUID        NOT NULL,

    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,
    replaced_by UUID        REFERENCES refresh_tokens (id) ON DELETE SET NULL,

    user_agent  VARCHAR(255),
    ip          VARCHAR(45),

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Every /refresh looks a token up by its hash.
CREATE UNIQUE INDEX ux_refresh_tokens_hash ON refresh_tokens (token_hash);

-- Reuse detection revokes an entire family in one statement.
CREATE INDEX ix_refresh_tokens_family ON refresh_tokens (family_id);

-- Suspension / password reset revokes every token a user holds.
CREATE INDEX ix_refresh_tokens_user ON refresh_tokens (user_id);


-- ────────────────────────────────────────────────────────────────────────────
-- email_verification_tokens
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE email_verification_tokens
(
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_email_verification_hash ON email_verification_tokens (token_hash);
CREATE INDEX ix_email_verification_user ON email_verification_tokens (user_id);


-- ────────────────────────────────────────────────────────────────────────────
-- password_reset_tokens
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE password_reset_tokens
(
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_password_reset_hash ON password_reset_tokens (token_hash);
CREATE INDEX ix_password_reset_user ON password_reset_tokens (user_id);


-- ────────────────────────────────────────────────────────────────────────────
-- outbox_events
--
-- Written in the SAME transaction as the business change, published to Kafka
-- afterwards by a scheduled poller. This is what makes event publishing
-- survive a crash between the commit and the send.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE outbox_events
(
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    aggregate_type VARCHAR(32) NOT NULL,
    aggregate_id   UUID        NOT NULL,
    event_type     VARCHAR(48) NOT NULL,
    payload        JSONB       NOT NULL,

    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at   TIMESTAMPTZ,
    attempts       INTEGER     NOT NULL DEFAULT 0,

    CONSTRAINT ck_outbox_aggregate_type CHECK (aggregate_type IN ('USER'))
);

-- Partial index: the publisher only ever scans unpublished rows, so only those
-- are indexed. It stays tiny however large the table grows, and rows drop out
-- of it automatically once published. No MySQL equivalent.
CREATE INDEX ix_outbox_unpublished
    ON outbox_events (created_at)
    WHERE published_at IS NULL;
